language: java
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
before_deploy:
- mvn -DskipTests package
- export RELEASE_FILE=$(ls target/acumen-indexer-*-jar-with-dependencies.jar)
deploy:
  provider: releases
  api_key:
    secure: CKf+lyyEbeztoGhAS9aiKo0W4/HE9rKPu3WHt0J2WgLSkobJT82J60G4E9gLtUiMx42PYSpLo/1oyraQvia4AY/xQxChiOOLoVqT+C12egYQpr7AVYuKvaEHBsoZVXNeqLaa7FkzJLgpZGBv1zWSP3i1IaT9cO4IghK125nZf/iKJpsI2sy1vHUn7jOM9I8fhJGtQMOa5lYVfaB+pfF35IUfoTlSf1jSeUVeCyEIWr3Z9RHE2hBzf0m8xrnnJnx1SQOWZefqwW9VsVx7QHBP0bXsRQPdb6J9JSWnPloAnBi2YWieuQ8hPFswzHzPyWJWDxj8KxcEYMvNTO/kOhofXdJeNPgQv9/JBVN6UMo2mZTHnj8QeSfbsPfMsmgsjL8AtcSQhAzec0jPue7xdZbb817mUtOo/8Ptg2zIiCI4DqvpYuGWiJbMoPzRx9OgmU+92Dvw90DFpk/gVGe9cSoVTNKrc0bHzPVixUd4roqvtFDm2arpSgLp0rjGl+/uGthFOT4cRHmw5hS8F0VsRKmM0JhApzQFpgHFImvBztxzwjwG/QGXYhcjotXyWC+UmeB0ssYx9AYs9hczPYCK0lwXRUz+VN/FxZmv9D3vmdqaJXoC4GoDoGJdj9qJIIcOTl6q1xTha/+kvRJ4gp7Ud27NGD2Gi0X3PFx+BDYwxkoN9AI=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    repo: AcumenProject/acumen-indexer